# Generated by Django 2.2.2 on 2019-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='student name', max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
